spring.application.name=tea-service
server.port=8089

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
#Nado li?
management.metrics.tags.application=${spring.application.name}

management.prometheus.metrics.export.enabled=true
