{
 "title": "Tea Service",
 "refresh": "5s",
 "panels": [
  {
   "title": "JVM Used Memory",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    { "expr": "jvm_memory_used_bytes" }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count"
    }
   ]
  },
  {
   "title": "Application Uptime",
   "type": "stat",
   "gridPos": { "x": 0, "y": 8, "w": 6, "h": 4 },
   "targets": [
    { "expr": "process_uptime_seconds" }
   ]
  }
 ]
}